#!/usr/bin/env python3

from AoMatches import *

# 2021-02-21
# scrap_match_data("https://ausopen.com/match/2021-daniil-medvedev-vs-stefanos-tsitsipas-ms602")
# scrap_match_data("https://ausopen.com/match/2021-novak-djokovic-vs-aslan-karatsev-ms601")
# scrap_match_data("https://ausopen.com/match/2021-stefanos-tsitsipas-vs-rafael-nadal-ms504")
# scrap_match_data("https://ausopen.com/match/2021-andrey-rublev-vs-daniil-medvedev-ms503")
# scrap_match_data("https://ausopen.com/match/2021-grigor-dimitrov-vs-aslan-karatsev-ms502")
# scrap_match_data("https://ausopen.com/match/2021-novak-djokovic-vs-alexander-zverev-ms501")
# scrap_match_data("https://ausopen.com/match/2021-novak-djokovic-vs-daniil-medvedev-ms701")
# scrap_match_data("https://ausopen.com/match/2021-fabio-fognini-vs-rafael-nadal-ms408")
# scrap_match_data("https://ausopen.com/match/2021-stefanos-tsitsipas-vs-matteo-berrettini-ms407")
# scrap_match_data("https://ausopen.com/match/2021-dominic-thiem-vs-grigor-dimitrov-ms403")
# scrap_match_data("https://ausopen.com/match/2021-novak-djokovic-vs-milos-raonic-ms401")
# scrap_match_data("https://ausopen.com/match/2021-felix-auger-aliassime-vs-aslan-karatsev-ms404")
# scrap_match_data("https://ausopen.com/match/2021-dusan-lajovic-vs-alexander-zverev-ms402")
# scrap_match_data("https://ausopen.com/match/2021-mackenzie-mcdonald-vs-daniil-medvedev-ms406")
# scrap_match_data("https://ausopen.com/match/2021-andrey-rublev-vs-casper-ruud-ms405")

# day 6
# scrap_match_data("https://ausopen.com/match/2021-filip-krajinovic-vs-daniil-medvedev-ms312")
# scrap_match_data("https://ausopen.com/match/2021-cameron-norrie-vs-rafael-nadal-ms316")
# scrap_match_data("https://ausopen.com/match/2021-andrey-rublev-vs-feliciano-lopez-ms309")
# scrap_match_data("https://ausopen.com/match/2021-fabio-fognini-vs-alex-de-minaur-ms315")
# scrap_match_data("https://ausopen.com/match/2021-stefanos-tsitsipas-vs-mikael-ymer-ms313")
# scrap_match_data("https://ausopen.com/match/2021-karen-khachanov-vs-matteo-berrettini-ms314")
# scrap_match_data("https://ausopen.com/match/2021-casper-ruud-vs-radu-albot-ms310")
# scrap_match_data("https://ausopen.com/match/2021-lloyd-harris-vs-mackenzie-mcdonald-ms311")

# day 5
# scrap_match_data("https://ausopen.com/match/2021-adrian-mannarino-vs-alexander-zverev-ms304")
# scrap_match_data("https://ausopen.com/match/2021-novak-djokovic-vs-taylor-fritz-ms301")
# scrap_match_data("https://ausopen.com/match/2021-grigor-dimitrov-vs-pablo-carreno-busta-ms306")
# scrap_match_data("https://ausopen.com/match/2021-denis-shapovalov-vs-felix-auger-aliassime-ms307")
# scrap_match_data("https://ausopen.com/match/2021-aslan-karatsev-vs-diego-schwartzman-ms308")
# scrap_match_data("https://ausopen.com/match/2021-dominic-thiem-vs-nick-kyrgios-ms305")
# scrap_match_data("https://ausopen.com/match/2021-marton-fucsovics-vs-milos-raonic-ms302")
# scrap_match_data("https://ausopen.com/match/2021-pedro-martinez-vs-dusan-lajovic-ms303")

# day 4
# scrap_match_data("https://ausopen.com/match/2021-stefanos-tsitsipas-vs-thanasi-kokkinakis-ms225")
# scrap_match_data("https://ausopen.com/match/2021-michael-mmoh-vs-rafael-nadal-ms232")
# scrap_match_data("https://ausopen.com/match/2021-tomas-machac-vs-matteo-berrettini-ms228")
# scrap_match_data("https://ausopen.com/match/2021-pablo-cuevas-vs-alex-de-minaur-ms230")
# scrap_match_data("https://ausopen.com/match/2021-cameron-norrie-vs-roman-safiullin-ms231")
# scrap_match_data("https://ausopen.com/match/2021-andrey-rublev-vs-thiago-monteiro-ms217")
# scrap_match_data("https://ausopen.com/match/2021-fabio-fognini-vs-salvatore-caruso-ms229")
# scrap_match_data("https://ausopen.com/match/2021-roberto-carballes-baena-vs-daniil-medvedev-ms224")
# scrap_match_data("https://ausopen.com/match/2021-karen-khachanov-vs-ricardas-berankis-ms227")
# scrap_match_data("https://ausopen.com/match/2021-alexei-popyrin-vs-lloyd-harris-ms221")
# scrap_match_data("https://ausopen.com/match/2021-christopher-oconnell-vs-radu-albot-ms220")
# scrap_match_data("https://ausopen.com/match/2021-feliciano-lopez-vs-lorenzo-sonego-ms218")
# scrap_match_data("https://ausopen.com/match/2021-filip-krajinovic-vs-pablo-andujar-ms223")
# scrap_match_data("https://ausopen.com/match/2021-mackenzie-mcdonald-vs-borna-coric-ms222")
# scrap_match_data("https://ausopen.com/match/2021-casper-ruud-vs-tommy-paul-ms219")
# scrap_match_data("https://ausopen.com/match/2021-carlos-alcaraz-vs-mikael-ymer-ms226")

# day 3
# scrap_match_data("https://ausopen.com/match/2021-novak-djokovic-vs-frances-tiafoe-ms201")
# scrap_match_data("https://ausopen.com/match/2021-maxime-cressy-vs-alexander-zverev-ms208")
# scrap_match_data("https://ausopen.com/match/2021-dominic-thiem-vs-dominik-koepfer-ms209")
# scrap_match_data("https://ausopen.com/match/2021-grigor-dimitrov-vs-alex-bolt-ms211")
# scrap_match_data("https://ausopen.com/match/2021-stan-wawrinka-vs-marton-fucsovics-ms203")
# scrap_match_data("https://ausopen.com/match/2021-nick-kyrgios-vs-ugo-humbert-ms210")
# scrap_match_data("https://ausopen.com/match/2021-alexandre-muller-vs-diego-schwartzman-ms216")
# scrap_match_data("https://ausopen.com/match/2021-reilly-opelka-vs-taylor-fritz-ms202")
# scrap_match_data("https://ausopen.com/match/2021-james-duckworth-vs-felix-auger-aliassime-ms214")
# scrap_match_data("https://ausopen.com/match/2021-adrian-mannarino-vs-miomir-kecmanovic-ms207")
# scrap_match_data("https://ausopen.com/match/2021-denis-shapovalov-vs-bernard-tomic-ms213")
# scrap_match_data("https://ausopen.com/match/2021-corentin-moutet-vs-milos-raonic-ms204")
# scrap_match_data("https://ausopen.com/match/2021-jiri-vesely-vs-pablo-carreno-busta-ms212")
# scrap_match_data("https://ausopen.com/match/2021-alexander-bublik-vs-dusan-lajovic-ms206")
# scrap_match_data("https://ausopen.com/match/2021-emil-ruusuvuori-vs-pedro-martinez-ms205")
# scrap_match_data("https://ausopen.com/match/2021-egor-gerasimov-vs-aslan-karatsev-ms215")

# day 2
# scrap_match_data("https://ausopen.com/match/2021-laslo-djere-vs-rafael-nadal-ms164")
# scrap_match_data("https://ausopen.com/match/2021-stefanos-tsitsipas-vs-gilles-simon-ms149")
# scrap_match_data("https://ausopen.com/match/2021-vasek-pospisil-vs-daniil-medvedev-ms148")
# scrap_match_data("https://ausopen.com/match/2021-kevin-anderson-vs-matteo-berrettini-ms156")
# scrap_match_data("https://ausopen.com/match/2021-tennys-sandgren-vs-alex-de-minaur-ms160")
# scrap_match_data("https://ausopen.com/match/2021-andrey-rublev-vs-yannick-hanfmann-ms133")
# scrap_match_data("https://ausopen.com/match/2021-radu-albot-vs-roberto-bautista-agut-ms140")
# scrap_match_data("https://ausopen.com/match/2021-casper-ruud-vs-jordan-thompson-ms137")
# scrap_match_data("https://ausopen.com/match/2021-david-goffin-vs-alexei-popyrin-ms141")
# scrap_match_data("https://ausopen.com/match/2021-thanasi-kokkinakis-vs-soonwoo-kwon-ms150")
# scrap_match_data("https://ausopen.com/match/2021-mikael-ymer-vs-hubert-hurkacz-ms152")
# scrap_match_data("https://ausopen.com/match/2021-fabio-fognini-vs-pierre-hugues-herbert-ms157")
# scrap_match_data("https://ausopen.com/match/2021-pablo-cuevas-vs-andreas-seppi-ms159")
# scrap_match_data("https://ausopen.com/match/2021-mackenzie-mcdonald-vs-marco-cecchinato-ms143")
# scrap_match_data("https://ausopen.com/match/2021-christopher-oconnell-vs-jan-lennard-struff-ms139")
# scrap_match_data("https://ausopen.com/match/2021-li-tu-vs-feliciano-lopez-ms135")
# scrap_match_data("https://ausopen.com/match/2021-karen-khachanov-vs-aleksandar-vukic-ms153")
# scrap_match_data("https://ausopen.com/match/2021-thiago-monteiro-vs-andrej-martin-ms134")
# scrap_match_data("https://ausopen.com/match/2021-nikoloz-basilashvili-vs-tommy-paul-ms138")
# scrap_match_data("https://ausopen.com/match/2021-filip-krajinovic-vs-robin-haase-ms145")
# scrap_match_data("https://ausopen.com/match/2021-ilya-ivashka-vs-roman-safiullin-ms162")
# scrap_match_data("https://ausopen.com/match/2021-guido-pella-vs-borna-coric-ms144")
# scrap_match_data("https://ausopen.com/match/2021-michael-mmoh-vs-viktor-troicki-ms163")
# scrap_match_data("https://ausopen.com/match/2021-sam-querrey-vs-lorenzo-sonego-ms136")
# scrap_match_data("https://ausopen.com/match/2021-tomas-machac-vs-mario-vilella-martinez-ms155")
# scrap_match_data("https://ausopen.com/match/2021-pablo-andujar-vs-quentin-halys-ms146")
# scrap_match_data("https://ausopen.com/match/2021-roberto-carballes-baena-vs-attila-balazs-ms147")
# scrap_match_data("https://ausopen.com/match/2021-henri-laaksonen-vs-salvatore-caruso-ms158")
# scrap_match_data("https://ausopen.com/match/2021-lloyd-harris-vs-mikael-torpegaard-ms142")
# scrap_match_data("https://ausopen.com/match/2021-botic-van-de-zandschulp-vs-carlos-alcaraz-ms151")
# scrap_match_data("https://ausopen.com/match/2021-ricardas-berankis-vs-sumit-nagal-ms154")
# scrap_match_data("https://ausopen.com/match/2021-daniel-evans-vs-cameron-norrie-ms161")

# day 1
# scrap_match_data("https://ausopen.com/match/2021-dominic-thiem-vs-mikhail-kukushkin-ms117")
# scrap_match_data("https://ausopen.com/match/2021-novak-djokovic-vs-jeremy-chardy-ms101")
# scrap_match_data("https://ausopen.com/match/2021-marcos-giron-vs-alexander-zverev-ms116")
# scrap_match_data("https://ausopen.com/match/2021-denis-shapovalov-vs-jannik-sinner-ms125")
# scrap_match_data("https://ausopen.com/match/2021-stan-wawrinka-vs-pedro-sousa-ms105")
# scrap_match_data("https://ausopen.com/match/2021-frederico-ferreira-silva-vs-nick-kyrgios-ms119")
# scrap_match_data("https://ausopen.com/match/2021-federico-coria-vs-milos-raonic-ms108")
# scrap_match_data("https://ausopen.com/match/2021-kei-nishikori-vs-pablo-carreno-busta-ms124")
# scrap_match_data("https://ausopen.com/match/2021-corentin-moutet-vs-john-millman-ms107")
# scrap_match_data("https://ausopen.com/match/2021-grigor-dimitrov-vs-marin-cilic-ms121")
# scrap_match_data("https://ausopen.com/match/2021-alex-bolt-vs-norbert-gombos-ms122")
# scrap_match_data("https://ausopen.com/match/2021-frances-tiafoe-vs-stefano-travaglia-ms102")
# scrap_match_data("https://ausopen.com/match/2021-miomir-kecmanovic-vs-kamil-majchrzak-ms114")
# scrap_match_data("https://ausopen.com/match/2021-alexandre-muller-vs-juan-ignacio-londero-ms131")
# scrap_match_data("https://ausopen.com/match/2021-damir-dzumhur-vs-james-duckworth-ms127")
# scrap_match_data("https://ausopen.com/match/2021-elias-ymer-vs-diego-schwartzman-ms132")
# scrap_match_data("https://ausopen.com/match/2021-benoit-paire-vs-egor-gerasimov-ms129")
# scrap_match_data("https://ausopen.com/match/2021-yuichi-sugita-vs-bernard-tomic-ms126")
# scrap_match_data("https://ausopen.com/match/2021-gianluca-mager-vs-aslan-karatsev-ms130")
# scrap_match_data("https://ausopen.com/match/2021-kimmer-coppejans-vs-jiri-vesely-ms123")
# scrap_match_data("https://ausopen.com/match/2021-reilly-opelka-vs-yen-hsun-lu-ms103")
# scrap_match_data("https://ausopen.com/match/2021-aljaz-bedene-vs-alexander-bublik-ms111")
# scrap_match_data("https://ausopen.com/match/2021-gael-monfils-vs-emil-ruusuvuori-ms109")
# scrap_match_data("https://ausopen.com/match/2021-cedrik-marcel-stebe-vs-felix-auger-aliassime-ms128")
# scrap_match_data("https://ausopen.com/match/2021-marton-fucsovics-vs-marc-polmans-ms106")
# scrap_match_data("https://ausopen.com/match/2021-dominik-koepfer-vs-hugo-dellien-ms118")
# scrap_match_data("https://ausopen.com/match/2021-albert-ramos-vinolas-vs-taylor-fritz-ms104")
# scrap_match_data("https://ausopen.com/match/2021-taro-daniel-vs-maxime-cressy-ms115")
# scrap_match_data("https://ausopen.com/match/2021-adrian-mannarino-vs-dennis-novak-ms113")
# scrap_match_data("https://ausopen.com/match/2021-sergiy-stakhovsky-vs-dusan-lajovic-ms112")
# scrap_match_data("https://ausopen.com/match/2021-yoshihito-nishioka-vs-pedro-martinez-ms110")
# scrap_match_data("https://ausopen.com/match/2021-yasutaka-uchiyama-vs-ugo-humbert-ms120")
